driver:
  name: ec2
  aws_ssh_key_id: mynewkeypair # key pair name
  region: ap-south-1 # region code of aws
  availability_zone: ap-south-1b # availability_zone 
  subnet_id: subnet-26c84f6a # subnet-id noted from above steps
  instance_type: t2.micro # as it is free instance type
  image_id: ami-0a574895390037a62 # image id of ubuntu
  security_group_ids: ["sg-08214c50f3c724be7"]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

transport:
  ssh_key: ./mynewkeypair.pem # relative path to pem file
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu # username from ami-id

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[openmrs::java8]
      - recipe[openmrs::mysql]
      - recipe[openmrs::tomcat8]
      - recipe[openmrs::warfile]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

