#https://docs.getsaleor.com/en/latest/gettingstarted/installation-linux.html

---
- hosts: saleor
  become: yes
  tasks:
  - name: install python3 
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - build-essential
      - python3-dev
      - python3-pip
      - python3-cffi
      - libcairo2
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libgdk-pixbuf2.0-0
      - libffi-dev
      - shared-mime-info
      